name: "KiBot - Generate schematic files"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Design version"
        required: true
        default: "pre-release"

jobs:
  Documentation:
    env:
      # Set this to your local timezone. See https://www.wikiwand.com/en/List_of_tz_database_time_zones for valid strings.
      Timezone: America/New_York
      # Set this to the output folder for all of the generated files. Unless you have a very
      # good reason to change this you should leave it as KiBotOutput.
      OutputFolder: KiBotOutput
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v2

      # Get the current date in the timezone specified above, for use later.
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d')"

      # Get the version of the GitHub release when run in a release context
      - name: Get GitHub release version
        id: get_github_version
        uses: battila7/get-version-action@v2
        if: startsWith(github.ref, 'refs/tags/')

      - name: Store GitHub release version
        id: save_github_version
        run: echo "version=${{ steps.get_github_version.outputs.version }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      # Get the version from the workflow input when run manually as a workflow.
      - name: Store workflow version
        id: save_workflow_version
        run: echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/') == false

      # Pulls MTE kibot_files from Github for use with Kibot
      - name: Pull kibot_files
        uses: actions/checkout@master
        with:
          repository: MicroType-Engineering/kibot_files
          token: ${{ secrets.KiBot_Secret }}
          path: './kibot_files'

      # Run KiBot to generate all the files.
      - name: Generate schematic outputs
        uses: MicroType-Engineering/KiBot@stable
        with:
          config: kibot_files/schematic-files.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: kicad_proj/${{ github.event.repository.name }}.kicad_sch
          board: kicad_proj/${{ github.event.repository.name }}.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}_${{ github.event.inputs.version }}_${{ steps.date.outputs.date }}
          path: ${{ env.OutputFolder }}/**
