# This workflow generates documentation (PDFs, interactive BOMs, board images) and fabrication
# files for JLCPCB and PCBWay. The version number and date of the design is automatically
# updated in the schematic file and on the PCB based on the GitHub release version and date.

# To use this workflow in your own repo you need to edit the environment variables in the env: section
# below.
name: "KiBot - Generate All Files"

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Design version"
        required: true
        default: "pre-release"

jobs:
  FabricationAndDocumentation:
    env:
      # Set this to your local timezone. See https://www.wikiwand.com/en/List_of_tz_database_time_zones for valid strings.
      Timezone: America/Los_Angeles
      # Set this to the output folder for all of the generated files. Unless you have a very
      # good reason to change this you should leave it as KiBotOutput.
      OutputFolder: KiBotOutput
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v2

      # Get the current date in the timezone specified above, for use later.
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d')"

      # Get the version of the GitHub release when run in a release context
      - name: Get GitHub release version
        id: get_github_version
        uses: battila7/get-version-action@v2
        if: startsWith(github.ref, 'refs/tags/')

      - name: Store GitHub release version
        id: save_github_version
        run: echo "version=${{ steps.get_github_version.outputs.version }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      # Get the version from the workflow input when run manually as a workflow.
      - name: Store workflow version
        id: save_workflow_version
        run: echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/') == false

      
      #Changes the MTE_LIB_DIR to match the path for the libraries we pull
      - name: Change lib paths
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ${MTE_LIB_DIR}
          replace: MTE_LIB_DIR
          regex: false
      
      # Pulls MTE KiCad libs from Github for use with 3D STEPs
      - name: Pull kicad_libs
        uses: actions/checkout@master
        with:
          repository: MicroType-Engineering/kicad-libs
          token: ${{ secrets.KiBot_Secret }}
          path: './MTE_LIB_DIR'

      # Pulls MTE kibot_files from Github for use with Kibot
      - name: Pull kibot_files
        uses: actions/checkout@master
        with:
          repository: MicroType-Engineering/kibot_files
          token: ${{ secrets.KiBot_Secret }}
          path: './kibot_files'

      # Actually run KiBot to generate all the files.
      - name: Generate documentation and fabrication files
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: kibot_files/all_files.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: kicad_proj/${{ github.event.repository.name }}.kicad_sch
          board: kicad_proj/${{ github.event.repository.name }}.kicad_pcb

      # Install the zip command line tool to package up the output
      - name: Install zip
        uses: montudor/action-zip@v1

      # Zip all the documentation. Any files in the BOM, PDFs, and Renders subfolder
      # are automatically included.
      - name: Zip documentation
        run: zip -qq -r "../${{ github.event.repository.name }}_${{ steps.get_github_version.outputs.version }}_${{ steps.date.outputs.date }}.zip" PCB-Files Schematic-Files
        working-directory: ${{ env.OutputFolder }}

      # Upload all the zip files to the release.
      - name: Upload release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ github.event.repository.name }}_${{ steps.get_github_version.outputs.version }}_${{ steps.date.outputs.date }}.zip

      # Archive all the artifacts from output and attach to the action's results.
      # This is so they're made available when this workflow is run manually from the
      # GitHub actions page.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}_${{ github.event.inputs.version }}_${{ steps.date.outputs.date }}
          path: ${{ env.OutputFolder }}/**
